### ISSUE TITLE
Lumen volume of an organoid modified when calling energy_min on its copy

### ISSUE THREAD

**Issue by felixquinton** [DamCB/tyssue#132]
While working on an optimization procedure I stumbled upon something weird.
My framework is as follow : 
1) I initiate an AnnularSheet.
2) I create a copy of this AnnularSheet.
3) I call Solver.find_energy_min on the copy.
After this step the lumen volume of the original AnnularSheet, stored in the settings dictionnary, is modified.
The issue is demonstrated in the attached notebook.
[issue_lumen_vol.ipynb.tar.gz](https://github.com/DamCB/tyssue/files/2996155/issue_lumen_vol.ipynb.tar.gz)

**Comment by glyg** [comment]
Yes this is due to the fact that the `copy` method of the Sheet object passes a reference of the original specs dictionary and not a copy. I'll fix it in the next release (or you can open a PR if you want, it's an easy fix)
Thanks for the report!

**Comment by glyg** [comment]
closed by #133
