### ISSUE TITLE
T1 transition in solver change tissue axis 

### ISSUE THREAD

**Issue by sophietheis** [DamCB/tyssue#142]
When I done a simulation with the QSSolver with T1 transition. The axis of the tissue change between simulation step. We can see it in the images below. It is for simulation time 13, 14 and 15. And graphes are made in zx axis. 
t13
![problemt13](https://user-images.githubusercontent.com/17041165/60335603-9b3f2500-999e-11e9-83a1-b0ffd6354889.png)
t14
![problemt14](https://user-images.githubusercontent.com/17041165/60335619-a42ff680-999e-11e9-965f-7dabbfc78c41.png)
t15
![problemt15](https://user-images.githubusercontent.com/17041165/60335626-a7c37d80-999e-11e9-881c-2fb552578d2e.png)

There is no problem without T1 transition.

**Comment by glyg** [comment]
This is super strange!!!

**Comment by glyg** [comment]
looks like it solved itself ?Computer science is not an exact science :p
