### ISSUE TITLE
history.retrieve(i) doesn't correspond to the i_ème simulation step

### ISSUE THREAD

**Issue by sophietheis** [DamCB/tyssue#149]
The simulation run as expected with the euler solver when I checked at different moment during the process. I tested with some simple event, few cells reduce their apical surface until reached a threashold. But when I use the history.retrieve, I can only have 3 differents set of values. I guess it is correspond to the first time, a middle time and the last time. This 3 set are in position 0, 1 and 2 when I call history.retrieve. When I call history.retrieve(i) with i>2, I have the same data as in position 2. 
I checked history.face_h at different simulation time and it fits with what I am expected.

**Comment by sophietheis** [comment]
Well, I understand... I did not use correctly the retrieve method... Two days to understand why I don't have what I am expected, and 20min after open the issue, I remark that I don't use correctly the method... At least, now I have a very good understanding of the history class. :D

**Comment by glyg** [comment]
Was the docstring not clear enough? Could you improve it so we don't do that same error again (stressing that it's the time not the index). Maybe an index keyword arg would be nice?

**Comment by sophietheis** [comment]
I think I was convinced to used index in the method, because of this line `solver.history.time_stamps.shape` when I started to study the EulerSolver... 
Maybe we can use a warning message if the time pass through parameter is very big according to the ending time ? Because I think it is simpler to use real time arg than index arg.

**Comment by glyg** [comment]
yep maybe only warning if the argument is greater than the maximum time would be ok.
