### ISSUE TITLE
Use exact predicates

### ISSUE THREAD

**Issue by sloriot** [DamCB/tyssue#158]
Hi,

just a remark you should replace `CGAL::Simple_cartesian<double>` with `CGAL::Exact_predicates_inexact_constructions_kernel.h` if you want to guarantee that the result is correct. However, you should expect a slow down.

https://github.com/DamCB/tyssue/blob/4e5668be262205f110114cf3a95facf653120eab/tyssue/collisions/cpp/c_collisions.cpp#L22

**Comment by glyg** [comment]
Thanks a lot for the insight! This is actually something a bit mysterious to me whet exact/inexact entails in CGAL. Does this means there will be a lot of false positives?

**Comment by sloriot** [comment]
or some intersections will not be detected.
Basically, with the aforementioned kernel, rounding issues are taken into account when using predicates to make sure that the answer is true.

**Comment by glyg** [comment]
ok thanks! I'll make the change shortly!
