### ISSUE TITLE
Ply format reader

### ISSUE THREAD

**Issue by EptmSIM** [DamCB/tyssue#170]
It will be helpful if we can add other input file format like .obj or .ply in order to convert them as geometry compatible with Tyssue. 
[Gedeon5.zip](https://github.com/DamCB/tyssue/files/4063845/Gedeon5.zip)

ply header exemple:
"""
ply
format ascii 1.0
element vertex 138 # list of the nodes (x, y, z)
property float x
property float y
property float z
element face 171 # list of the faces (vertex id list and area)
property list int int vertex_index 
property float area
element edge 276 # list of the edges (vertex id source, vertex id target, list of faces, vector normal)
property int source
property int target
property list int int face_index
property float length
element volume 32 # list of the cells (face id list)
property list int int face_index 
property int label
end_header
"""

**Comment by glyg** [comment]
After some tinkering and some more reflexion, I think the best strategy is to add [meshio](https://github.com/nschloe/meshio) as a dependency and write I/O with that (so less effort). I'll do this in the next release

**Comment by sophietheis** [comment]
This work is in progress in issue #188 .
I close this one.
