### ISSUE TITLE
Introduction Notebook link does not work

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#177]
A 404 error is received upon opening the link.

**Comment by glyg** [comment]
Hi @sniffo thank you for reporting this, I think it has to do with readthedocs not cloning the gihub repo recursicely, I'll try to fix that on Wednesday 

Best

Guillaume

**Comment by glyg** [comment]
Meanwhile the notebooks can be found here: https://nbviewer.jupyter.org/github/damcb/tyssue-demo/tree/master/

**Comment by sniffo** [comment]
Thank you @glyg for the link! Great work on the module.
