### ISSUE TITLE
Varying effector parameters within a single epithelium

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#179]
Inclusion of the method for applying different effector parameters to subsets of edges/faces/vertices within the same epithelium object in the documentation would be helpful

e.g. 
```py
# sets line tension for all the edges

sheet.edge_df["line_tension"] = 0.12

# set line tension only for negative source edges

sheet.edge_df.loc[sheet.edge_df['sx'] < 0, "line_tension"] = 0.24
```

**Comment by sophietheis** [comment]
There will be an explanation of varying effector parameters in this notebook demo [quasistatic_models](https://github.com/DamCB/tyssue-demo/blob/master/Quasistatic_models.ipynb) in the next release.
