### ISSUE TITLE
Published invagination module causes self-intersection in newer tyssue versions

### ISSUE THREAD

**Issue by btbest** [DamCB/tyssue#185]
The "invagination" module published in https://www.nature.com/articles/s41467-019-10720-0, repo https://github.com/DamCB/invagination
instructs to install tyssue from conda-forge,
`$ conda install -c conda-forge tyssue`
which installs tyssue-0.5.0 and this reproduces the published simulation perfectly.

Rerunning the same simulation with tyssue 0.7.0 instead of 0.5.0 causes the "is_relaxation" faces bordering the "is_mesoderm" faces to cross over the "furrow" once invaginated, then intersect through the faces of the opposite side and eventually stretch far out the model space (as seen here https://twitter.com/benediktbest/status/1258734133930610688).

I'm currently hunting for what was the change that causes this difference. (Full disclosure I disabled the collisions module because CMake was causing the pains of a thousand needles, but none of that code ever gets called in this simulation so that should not be the reason).

**Comment by btbest** [comment]
Think I found the problem, running a sim now to confirm.

In tyssue/behaviors/sheet/actions.py, `relax()` executes `increase()` on "prefered_area" without specifying a `bound`, version 0.5.0 didn't have an increase() function and had both the decrease of "contractility" and the increase of "prefered_area" conditional under `new_value >= bound`.

**Comment by glyg** [comment]
great! There is no need for a fix on tyssue side then?
@sophietheis do we need to do something in invagination?

Thanks for the report,
Guillaume

**Comment by btbest** [comment]
It's a fix in tyssue, will be making the pull request once I confirm that this is the issue!

**Comment by glyg** [comment]
ok great!
