### ISSUE TITLE
Any built-in methods to add/remove specific vertices, edges and cells and have all datasets updated accordingly?

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#191]
I am working on a strategy suggested by Guillaume to restrain a 2D tissue within a shape which involves finding edges that intersect with the shape outline, adding vertices to the intersections, performing cell divisions, and removing the cells outside the shape. However, I am unsure how to add or remove vertices/cells and have all the datasets updated afterward. Thanks for the help!

**Comment by glyg** [comment]
Hi @sniffo 

There is a `remove` method [here](https://github.com/DamCB/tyssue/blob/master/tyssue/core/objects.py#L652) that takes a list of edge indices as argument. There is also a `remove_face` function in `sheet` that take a face index as argument. 

If you have several faces to remove, it is better to first collect all the edges you want to remove (e.g. in a loop) and remove them in one go by calling the `remove` method.

Once you have called `remove`, call the `reset_index` and `reset_topo` methods. Eventually you can call the `sanitize` method to be sure you have a sane tissue.

Hope this helps

Best,

Guillaume

**Comment by sophietheis** [comment]
Hi,

There is a method to add vertices in the middle of the edge [here](https://github.com/DamCB/tyssue/blob/master/tyssue/topology/base_topology.py#L57). 
You can adapt it if you don't want to to add vertices in the middle of the edge by changing the position of the new vertex around [line 111](https://github.com/DamCB/tyssue/blob/master/tyssue/topology/base_topology.py#L111).

Best, 
Sophie.

**Comment by glyg** [comment]
Thanks Sophie, sorry @sniffo I forgot your question !
