### ISSUE TITLE
KeyError when running get_opposite on sheet retrieve from history 

### ISSUE THREAD

**Issue by sophietheis** [DamCB/tyssue#195]
KeyError 'edge' appears when running get_opposite on sheet retrieve from an history save. 
It appears because the index columns of edge_df is named 'index' and not 'edge'. 

It can be fixed by running `sheet.edge_df.index.rename("edge", inplace=True)` before running `sheet.get_opposite()`.

**Comment by glyg** [comment]
Thanks for the report - some operations drop the index name - maybe the easiest fix is to add the rename in `history.retrieve`
