### ISSUE TITLE
Noise in Sheet.planar_sheet_2d creates erratic cell shapes at the tissue boundaries

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#196]
Some cells at the tissue boundaries have very long edges extending outwards. This is likely due to the Voronoi object, which has really high vertex coordinates in voro.ridge_vertices associated with the outermost Voronoi centers.

**Comment by glyg** [comment]
Hi Tasnif,

Yeah that's due to Voronoi tessalation. What I usually do is go back to equilibrium and that fixes the problem. You can also do:

```py
sheet.sanitize(trim_borders=True)
```
And that should get rid of the vertices on the border with only 2 edges.

G

**Comment by sniffo** [comment]
Hi Guillaume, 

The sanitize method does not work as expected, it does remove those vertices, but the new edges formed also end up being very long. 

I have used the energy minimization to achieve this in the past. I believe using a minimal model with only a BorderElasticity effector on the boundary vertices would be a good way of dealing with the issue without affecting inner cells too much, instead of minimizing energy based on all models effectors. Is there any method to find indices of boundary vertices? I will try an implementation and see how that works - please let me know if this makes sense. 

Best, 
Tasnif

**Comment by glyg** [comment]
Hi Tasnif, 

You can look at the `get_extra_indices` method - that will give you the 'free' edges, i.e. the ones that do not have an opposite half edge (in fact, they or the ones for which `sheet.get_opposite() == -1` so you can use just that.

Also your idea sounds cool, so  if yo wish to implement that, please do!

Best

G.

**Comment by gcourcou** [comment]
Hello, I have come across this problem as well. The problem is that a voronoi tessellation at the edges of a region, when noise is introduced, has infinitely large polygons .  What I do is that I use the extract functions to get a subset of the tyssue. See extract_bounding_box in documentation.

**Comment by sniffo** [comment]
`import numpy as np
import tyssue
from tyssue import Sheet
from tyssue import PlanarGeometry
from tyssue import SheetGeometry
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
from IPython.display import Image
from scipy.spatial import Voronoi, voronoi_plot_2d

from tyssue import config, Sheet, SheetGeometry, History
from tyssue.behaviors.event_manager import EventManager
from tyssue.dynamics.factory import model_factory
from tyssue.dynamics import effectors
from tyssue.draw import sheet_view
from tyssue.generation.hexagonal_grids import hexa_grid2d

from tyssue.dynamics import PlanarModel

from tyssue.solvers.quasistatic import QSSolver
from tyssue.solvers.viscous import EulerSolver

sheet_2d = Sheet.planar_sheet_2d('planar', nx=10, ny=10, 
                                 distx=1, disty=1, noise = 0.05)

sheet_2d.sanitize(trim_borders=True)


sheet_2d = sheet_2d.extract_bounding_box(x_boundary= (0.0,10.0), y_boundary=(0.0,10.0), z_boundary=None, coords=['x', 'y', 'z'])

PlanarGeometry.update_all(sheet_2d)

fig, (ax) = plt.subplots(1, figsize = (6, 6))
fig, ax = sheet_view(sheet_2d, ax=ax,)
`

I have used the code above to try and achieve this but it does not seem to work, as the tissue geometry remains the same. Am I using the method correctly?

**Comment by sophietheis** [comment]
Hello,

Did you solve your problem ? 
You use `extract_bounding_box` correctly. So normally it should cut the tissue.
The problem is the order of action. You have to update the geometry before cutting the tissue.

Sophie.

**Comment by sniffo** [comment]
Hi Sophie,

Yes, I was able to figure it out. Thank you!

Tasnif
