### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by glyg** [DamCB/tyssue#2]
## Main hurdle (in my view):

Having a **single data representation** (in the sense of the underlying data structure, I/O and view) for **multiple physical models** of the epithelium. 

### Core (frontend) data:

Four pandas DataFrame objects:

* [X] `cell_df`
* [X] `face_df`
* [X] `vert_df`
* [X] `edge_df`

Those dataframes are contained in a `datasets` dictionary, with `cell`, `face`, `vert` and `edge` as respective keys. 

### Specification

The various options for a simulation are stored in a nested dictionary called `specs`, with `cell`, `face`, `vert` and `edge` and `settings` as keys

### Core structure (or things that shouldn't move):
* `Epithelium` object (the whole mesh):
  - `datasets` -- A dictionary of the above mentioned dataframes.
  - `specs` -- A nested dictionary containing the specification and configuration options.  

_Note_ that specific parts of the epithelium, for example the various sheets (apical, basal or sagital) could be isolated or manipulated by the use of [boolean marks](http://doc.cgal.org/latest/Combinatorial_map/index.html#title15), reminiscent of graph_tool's edge filters.

## Events or Behaviors?

see comment bellow

### Behaviors / signals

* `Behavior` base class
 - triggered by user, the simulation scenario or in response to a signal
 - produces `Changes` in Epithelium (such as a change in topology / state space / state vector/ attributes)
 - in quasi-static models, triggers a new optimization

Two classes of `Changes` can take place:

* `AttributeChange` : a change in the cells or junction attributes, for example:
 - `CellGrowth` / `CellShrink` for cells
 - `TensionIncrease` for junctions

* `TopologicalChange`: Changes the model topology, thus the space state.
 - `CellDivision`
 - `T1Transition`
 - `CellEllimination`: a cell is removed from the tissue, or a specific tissue sheet 

* `Signal`
 - is sent by a `Cell` to it's neighbors (notion of propagation)
 - can trigger a behavior (such as a `TensionIncrease` event in neighbouring cells as happens in apoptotic cells).

### Models

Models are implemented functionnaly, there are no class associated

###  Graphical representation

Here we'll use a functional approach. We plan on using both `vispy` and `matplotlib`

* `EpitheliumView` interfaces (or adapter?)
  - adapts an `Epithelium` object to be passed to viewing functions

## Speaking of interfaces

Good modular design will require some care in the interplay between the various elements both in C++ and python. On that subject, @hadim pointed out [this discussion on vispy's ML](https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/vispy-dev/YfBwhTX9J-Q/nynt1igUlx4J)

Also of interest, [this vispy issue](https://github.com/sh4wn/vispy/issues/5)

## What's in Python, what's in C++ ?

The frontier might be moving, but basically:

| C++                         | Python                       |
|--------------------------|----------------------------|
|  core data structure | specific data              |
|                                 | I/O                             |
|                                 | graphical repr            |
|                                 | formal model             |
|  base geometry       |                                   |
|   solver                    |   solver                       |

The solver will likely be split up between python and C++, for example the computing of the gradient
could be done in C++, but the optimizer called by python, to profit from the ease of access to various algorithms in `scipy.optimize`

 

## Where we are so far

![Current class diagram](https://github.com/CellModels/tyssue/blob/master/doc/illus/class_diagram.png)

**Comment by hadim** [comment]
Nice project !

About compoment pattern design, see this link for a quick overview : https://python-utilities.readthedocs.org/en/latest/ebs.html

It seems that you want to use event/signal pattern for your simulation. I never implemented myself this kind of pattern (except when programming with Qt) but I wonder to know wether this technic is ok for quick and fast simulation.

Before going into this, I will strongly recommand you to estimate the overhead of such a technics ! You really should post the concept here : https://programmers.stackexchange.com/. I am sure some pattern design specialist could advise you !

**Comment by glyg** [comment]
Thanks for the comments!

I'll have a look to the component design link, I like the idea of avoiding the ZCA dependency, looks like an overkill. I need to clear up my ideas on the core interfacing object before that, and experiment some more with the python/C++ interface.

As for the events/signals, I too only have experience of that through UI design, but your question will let me elaborate a bit more on this aspect (I asked a question on IRC #python-fr yesterday about it).

The idea is not to have an event based software in a user interface sense, but just to use the event/callback pattern as a way to define a simulation flow, so (at least for the first version), one can define a simulation in terms of a scenario and some rules : From time 0 to 100: let some cell divide, from time 50 to 200, let those cells die with a certain probability, if this distance is lower than 0.3 µm, make a T1 transition. In the leg-joint code base, the scenario had to be very explicit, procedural. I hope this design will help making the creation of a simulation more flexible. 

A second hope I have is that this design can help in defining a less synchronous description of the simulation, i.e you can let a cell divide in some part of the epithelium and start a new event some where else. If the event is a single step process this is trivial, but if you have to pass through a series of step to end a single event, it becomes cumbersome with a procedural design. Eventually, I'm wondering if the use of things like AsyncIO could help doing something truly asynchronous, and hopefully parallelisable.

For now the idea is not to rely on an event library, but implement custom classes that just mimic this design.

Thanks again for the input, see you soon in Toulouse.

**Comment by glyg** [comment]
Maybe the term `Events` is poorly chosen.  Biologists talk more in terms of cell behavior, and it might make more sense, while retaining a multi-agent approach.

**Comment by glyg** [comment]
This is discussed extensively here:
http://damcb.com/gathering_thoughts_2.html

See notably:
![A new diagram](http://damcb.com/images/tyssue_data_management.svg)

**Comment by glyg** [comment]
After some time using the current API, I think it's ok. The above design is not up to date, due to name changes and other quirks.

I'm closing this Issue in favour of  #21 which is more documentation focused
