### ISSUE TITLE
Use the same dt parameter in viscous solver and sheet.settings

### ISSUE THREAD

**Issue by sophietheis** [DamCB/tyssue#201]
Maybe it will be useful when we set a `dt` value in the viscous solver, to update (or add) `dt` parameter in sheet.settings ? 
Otherwise we can have mixing `dt` values, for example `detach_vertices` take its `dt` value in `sheet.settings`, and the `dt` for the viscous solver is set in `solve` method. 
I would say that the `dt` value define in the `solve` method is the "correct" value, and it should be spread to `sheet.settings`.

**Comment by glyg** [comment]
yep you're right, can ou open a PR for that?

Thx
