### ISSUE TITLE
hard coded values in `relax` action

### ISSUE THREAD

**Issue by glyg** [DamCB/tyssue#210]
In the (deprecated) `relax` function:

https://github.com/DamCB/tyssue/blob/c0e6aea7f34fd4e0f9887656c1c63b05df69105d/tyssue/behaviors/sheet/actions.py#L320

Can we pass them as settings or infer them? (cc @sophietheis )

**Comment by sophietheis** [comment]
What do you mean ?

**Comment by sophietheis** [comment]
Ah for `initial_contractility` and `initial_prefered_area` ? I think we do not work with this value for now. So maybe we can remove it.

**Comment by glyg** [comment]
Ok I drop the action and test
