### ISSUE TITLE
Manually Setting Coordinates for Vertices

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#216]
If I were to manually set the position of a subset of vertices, for example, if I identify all boundary vertices on one side of a rectangular tissue, and then set the x or y coordinate to a given value for all of these vertices and generate a "pos" array and use the set_pos function, and then use update-all, will that update the entire tissue accordingly as it does in the EulerSolver? My goal is to have the vertices at the boundary all in a straight line while the rest of the tissue is noisy. I am concerned whether doing this will maintain the edge connections.

**Comment by glyg** [comment]
Hi @sniffo 
You can set the positions manually - you do not need to use the set_pos function, just assign the values to `eptm.vert_df.loc[your_vertex_indices, eptm.coords]` and update the geometry with `geom.update_all(eptm)` as you said.

Hope this answers your question,

Best

Guillaume

**Comment by sniffo** [comment]
Perfect thank you!
