### ISSUE TITLE
Problem with link to Bibtex

### ISSUE THREAD

**Issue by BenitoJG** [DamCB/tyssue#218]
Hi

I have a problem with acces this  link
![Captura](https://user-images.githubusercontent.com/76015227/105933340-db033e00-6013-11eb-8487-ab2e1a886413.JPG)

this error appears

![image](https://user-images.githubusercontent.com/76015227/105933525-303f4f80-6014-11eb-8e64-925d8fa5b57c.png)

I hoppe you can help me

**Comment by glyg** [comment]
Hi @BenitoJG thank you for pointing this out,

The bib file is here: https://github.com/damcb/tyssue/blob/master/doc/bibliography/tyssue.bib, and I need to update ii!

I'll fix the link in the README

Best

Guillaume

**Comment by BenitoJG** [comment]
thank you so much.
