### ISSUE TITLE
Functionality to avoid self-intersections and edges intersecting each other? 

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#219]
I was wondering if there were any topology functions to maintain the delauney triangulation or voronoi tesselation of the tissues. I am having some trouble with cell overlapping - perhaps functionality to prevent edge collisions and intersections might help? I am using the Euler Solver with the perimeter elasticity, area elasticity, line-tension, and a custom active force effectors. Please let me know if there is a strategy to deal with this issue.

**Comment by glyg** [comment]
Hi @sniffo I started working on that at some point last year, avoiding self-crossing would definitely be nice in 2D. I haven't time right now to look into it, although I think it is important. Honestly I will not have enough time before the summer for that. 
If you are interested in trying an implementation, you can look into: 

https://noonat.github.io/intersect/

CGAL has collision detection, and AABB trees that could be used (we started working on 3D collision also, but this needs a lot more work).

As a temporary solution, it is usually sufficient to lower your time step to avoid that kind of artifact. 

I'll try to find the notebook in which I started looking into that,

Best

Guillaume

**Comment by sniffo** [comment]
Understood, I will switch to a smaller time step and report what I find, the notebook would be quite helpful. Thank you for the help as always Guillaume! 

Best, 
Tasnif
