### ISSUE TITLE
Introducing holes or removing a patch of cells from within a tissue

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#220]
I was wondering if there is a way to remove cells from the middle of a tissue patch? I tried the remove_face method, but running the update_all method from the geometry classes seems to connect all the loose edges and fill the gap - is there a way to prevent this from happening - not quite sure which update method is causing it to close. 

Thanks, 
Tasnif

**Comment by glyg** [comment]
Hi Tasnif,

When you draw the sheet with `sheet_view(sheet, face={"visible": True}, edge={'headwidth': 1.0})` does the face appear? The only edges left should be the ones form the adjacent faces. You should also see the arrows from the edges

**Comment by sniffo** [comment]
![image](https://user-images.githubusercontent.com/20935700/106631722-05408880-654b-11eb-805a-3666c47013c6.png)
This is what it looks like after removing the edges

**Comment by sniffo** [comment]
After running update_all method:

![image](https://user-images.githubusercontent.com/20935700/106631911-35882700-654b-11eb-93c1-ed5fcb1136b0.png)

**Comment by sniffo** [comment]
I would like to connect the dangling edges. Or remove them and sanitize the inner border if you will.

**Comment by sniffo** [comment]
Apologies for multiple comments, but here it is with faces visible

![image](https://user-images.githubusercontent.com/20935700/106632510-d4148800-654b-11eb-825a-cdb856bcbccd.png)

**Comment by glyg** [comment]
IDK why all the edges are not deleted by the remove_faces method. I suspect that what you see is matplotlib replacing Nans by 0s.

What you can try after the remove_face is to apply `sheet.sanitize(trim_borders=True)` hopefully it should do what you want.
I think there is still something buggy in the remove_face method. Can you loolk if you have NaNs in sheet.edge_df?

**Comment by glyg** [comment]
Also it is not clear to me if you want to keep the partially deleted cells on you first graph

**Comment by sniffo** [comment]
No Nans in edge_df, I believe remove_face removes the face by collapsing all edges to a single vertex in the center. However, the method does not run update_all since it does not take geom as an argument, and that may be required to display the correct connections. 

`    # collapse all edges connected to the face vertices
    sheet.edge_df.replace({"srce": verts, "trgt": verts}, new_vert, inplace=True)  `  

The `sheet.sanitize` method does not work unfortunately

I do want to keep the partially deleted cells, their indices were not included when using remove_face. The missing edges are the edges shared by the deleted face and their neighbors. I have 

You can find the code in this notebook: https://github.com/sniffo/Tyssue-General-Notebooks/blob/main/Hole%20in%20Tissue.ipynb

**Comment by sniffo** [comment]
I propose an alternative method for removing a face, which simply removes the face itself, and only the half-edges associated with the face. This should achieve what I am trying to do, please let me know if that is incorrect. I will start working on this asap.

**Comment by glyg** [comment]
Oh yes you're right! Maybe the method could be caled drop_face or someting!

You can use the `remove` method that removes the edges (and the associated face)

Please open a PR when you have something if you don't mind (maybe also add a comment in remove_face docstring)

**Comment by sniffo** [comment]
I came up with the following, however, there seems to be an issue with removing multiple faces. Using sanitize or setting `trim_borders = True` removes some unwanted edges. 

This is what I have:

```
def drop_face(sheet, face, **kwargs):
    """
    Removes the face indexed by "face" and all associated edges
    """    
    edge = sheet.edge_df.loc[(sheet.edge_df['face'] == face)].index
    
     
    sheet.remove(edge, **kwargs)
```

Currently only takes one face as an argument, changing it to array-like for multiple faces should be simple. However, there is the following issue. The initial tissue:

![image](https://user-images.githubusercontent.com/20935700/106917490-4fa24080-66d6-11eb-8931-95afef48ba42.png)

After sequentially "dropping" the center face and its 5 neighbors:

![image](https://user-images.githubusercontent.com/20935700/106917606-6ea0d280-66d6-11eb-89a1-ea765f1d8df4.png)

After running sanitize with `trim_borders = True`:

![image](https://user-images.githubusercontent.com/20935700/106917703-85472980-66d6-11eb-9933-808842ffec21.png)

Seems that for the cells that have two border edges on the new "inner" border, the edges are simply removed and a new edge is not created. Currently trying to figure out why this might be.

**Comment by sniffo** [comment]
Apologies, I have figured out the issue here, it was the order of operations. Running `geom.update_all` after running sanitize seems to do the trick. 

![image](https://user-images.githubusercontent.com/20935700/106918607-554c5600-66d7-11eb-8444-04cc7626a5ab.png)

I will update the method to take a list of face indices and create the PR.

**Comment by glyg** [comment]
Great, thank you Tasnif

**Comment by glyg** [comment]
hi @sniffo did you have a chance to update your code, are you up to create a PR?
Thanks

Guillaume

**Comment by sniffo** [comment]
Hi @glyg sincere apologies, have not been working on simulations for a bit so I just saw this. The code has been updated I will put in the PR this weekend, 

Best, 
Tasnif

**Comment by glyg** [comment]
Hi Tasnif, I'm on holiday for tow more weeks, will review your PR then with great pleasure!
