### ISSUE TITLE
ENH: meshio export

### ISSUE THREAD

**Issue by glyg** [DamCB/tyssue#221]
no time to implement right now but here the code until I or someone else does:
```python
import meshio
def to_mesh(sheet):
    cell_types = {
        3: "triangle",
        4: "quad"}
    max_nsides = sheet.face_df["num_sides"].max() + 1
    cell_types.update(
        {
            i: f"polygon{i}" for i in range(5, max_nsides)
        }
    )
    sheet.reset_index(order=True)
    sheet.edge_df["f_sides"] = sheet.upcast_face("num_sides")
    cells = [
        ('line', sheet.edge_df[["srce", "trgt"]].to_numpy())    
    ]
    for n, edges in sheet.edge_df.groupby("f_sides"):
        polys = np.vstack(edges.groupby("face").apply(lambda e: e["srce"].values).values)
        cells.append((cell_types[n], polys))
    mesh = meshio.Mesh(points=sheet.vert_df[sheet.coords].to_numpy(), cells=cells)
    return mesh
```

**Comment by sophietheis** [comment]
Hey, 
I dig into old issues... I can add this function now. 
Do you remember if you plan to put it in [meshes.py](https://github.com/DamCB/tyssue/blob/master/tyssue/io/meshes.py) or make it a class method of [`Epithelium`](https://github.com/DamCB/tyssue/blob/master/tyssue/core/objects.py) ? 
As we already have method to do mesh in `Epithelium` class, I find it more logical to add it here. 

Sophie.

**Comment by glyg** [comment]
Good of you to dig into old issues (it's a bit dusty)... I would prefer to leave it out of the main class, in fact I think there is too much stuff in the main class & this makes it less modular, so I'd rather have this into the io module (plus this way we can make the meshio dependency optional and not central...)

**Comment by glyg** [comment]
So I think we should organize a 0.9 release with all that code  — plus tests :wink:
Then we should work towards a 1.0 release that would be the occasion to clean all up, better the docs etc.

I had a mail from someone at UCS (the same group George Coucourbetis is in) and they are using tyssue, plus there is Kyle plugin, so it could be cool to see who is really using that library and if we can find devs to help :)

In the longer term, I think it could be cool to port a good part of the core functions (topologies, geometry, dynamics) to a faster interface (either cython or straight up CGAL)... Maybe we can discuss that at some point.
 
What do you think?

**Comment by sophietheis** [comment]
I don't forget test :unamused: It is on my to-do list. And yes we can organise the 0.9 release with that. 

Sure, I have a todo list of thing that I want to do. I want to make the readme.md more "visual" and "attractive" :smiley: . And,  I don't know how yet, but I want to find a way to have `effectors` more easy to list and more easy to know what parameters is needed... I have scheme that we can add to the doc if you want too, like simple inheritance class diagram for geometry. It helps me when I wrote the 2D lateral geometry to know which class should be the parent class :smiley: 
![image](https://user-images.githubusercontent.com/17041165/201964189-ea184a81-54ff-4846-b35f-a5758cf0b3d0.png)

I also had a mail from someone at the Uni of Ljubljana who start to use tyssue, and I met someone at PLM in september that want to use tyssue too (also from Ljubljana if I remember well but not the same person). 

Yes, it could be nice to use faster interface. If it is CGAL it will complicate a bit the installation, but as we already use it for the collision solver, we can continue to use it ^^. 

We can plan a meeting later (maybe at the beginning of the year), to discuss and write a roadmap.

**Comment by sophietheis** [comment]
Maybe a "graphical user interface" is more interesting compare to use faster computation... Time to get a trainee to do the GUI ! :wink: 

Sure we can do some pub on twitter. Maybe with alink to a small form to survey what people/user want/expect from tyssue.
