### ISSUE TITLE
Some issue with ucoords in 0.8.1

### ISSUE THREAD

**Issue by btbest** [DamCB/tyssue#229]
I just pulled the 0.8.1 release and integrated the changes with my local files; after that my invagination sims no longer worked (the radial tension didn't work and vertices didn't get pulled towards the interior as a consequence).

I went through diffs with my backup to identify changes likely to cause this and found an initial culprit in behavior/factory.py:

```
def compute_gradient(eptm, components=False):
    norm_factor = eptm.specs["settings"].get("nrj_norm_factor", 1)

    #<begin section no longer present in 0.8.1>
    if not eptm.ucoords[0] in eptm.edge_df.columns:
        warnings.warn(
            "setting ucoords in grad computation," "please fix your specs"
        )
        #for uc in eptm.ucoords:
        eptm.edge_df[eptm.ucoords] = 0.0

    eptm.edge_df[eptm.ucoords] = eptm.edge_df[eptm.dcoords] / to_nd(
        eptm.edge_df["length"], eptm.dim
    )
    #<end section no longer present in 0.8.1>

    grads = [f.gradient(eptm) for f in effectors]
    if components:
        return grads
    #etc
```

The if-statement and the following statement to update the ucoords in edge_df were removed in 0.8.1; reintroducing them fixed it. I saw that there were changes related to ucoords in other files, so I suspect there was a design change (i.e. compute_gradient is not where the ucoords should be calculated), but now the ucoords don't actually end up getting updated in edge_df by the time compute_gradient is called.

--- I had another look. The other place I saw the ucoords was in base_geometry.py, which now has a new update_ucoords function. But sheet_geometry.py doesn't call update_ucoords in its update_all function, so I might just need to add a call there to fix it.

**Comment by btbest** [comment]
Yes, my last comment was accurate and adding that call to sheet_geometry.py fixed it. Happy to send a pull request a bit later :)

**Comment by sophietheis** [comment]
Great ! if you fixed it, we wait your PR. :D

**Comment by btbest** [comment]
Nevermind, it seems it's already been fixed...

**Comment by sophietheis** [comment]
Is your problem fixed ? We did not change the code recently...

**Comment by btbest** [comment]
Yes, I think there was just an issue with integrating the code changes from the new version; the required function call is actually already there in the current version on here.
