### ISSUE TITLE
Changing parameters over-time in the viscous solver?

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#232]
Is there any way to change certain parameters as the viscous solver is running? For example, if I wanted perimeter elasticity to change according to a function every 5 time units. Does not seem like it is immediately possible unless I am missing something.

**Comment by sophietheis** [comment]
Hi,
You can't do it directly. The easiest way is to declare a derived class from the base class `EuleurSolver` and adapt `solve` function. I copy/paste `solve`method from the base class and I add 2-3 lines as example to change parameter during simulation. 

For example : 
```python 

class MyEulerSolver(EulerSolver):
    def solve (self, tf, dt, on_topo_change=None, topo_change_args=()):
        self.eptm.settings["dt"] = dt
        for t in np.arange(self.prev_t, tf + dt, dt):

            # Add this part
            if t%5==0:
                self.eptm.face_df['perimeter_elasticity'] = 10*t-2
                
            pos = self.current_pos
            dot_r = self.ode_func(t, pos)
            if self.bounds is not None:
                dot_r = np.clip(dot_r, *self.bounds)
            pos = pos + dot_r * dt
            self.set_pos(pos)
            self.prev_t = t
            if self.manager is not None:
                self.manager.execute(self.eptm)
                self.geom.update_all(self.eptm)
                self.manager.update()

            if self.eptm.topo_changed:
                log.info("Topology changed")
                if on_topo_change is not None:
                    on_topo_change(*topo_change_args)
                self.eptm.topo_changed = False
            self.record(t)

``` 

I think this is the fastest way to do it. 
If you want to do more complex change during the simulation, I think it will be better and "cleaner" to use the same principle as the `on_topo_change` and `topo_change_args` parameters from `solve` method. 

Sophie.

**Comment by sniffo** [comment]
Makes sense, thank you! 
Best, 
Tasnif

**Comment by btbest** [comment]
I've done this similar to the original invagination module (DamCB/invagination):
```
#do stuff to set up sim
#and set up events with manager.append()
#then:
stop = num_frames
while (manager.current and t < stop):
     manager.execute()
     eulersolver.solve(1, 1)
     manager.update()
```
Is there anything problematic about this (programatically or conceptually/mathematically), i.e. just calling the solver for one time step and then proceeding with modifying the sheet's parameters in the manager's events, that I don't realise?

Cheers,
Bene

**Comment by sophietheis** [comment]
Methods `manager.execute()` and `manager.update()` are already called in `solve` method. 
I don't think it is a problem until you don't use `on_topo_change` parameters. If you use this parameter, `solve` method will not be able to track change in the topology and never go throw `on_topo_change` function. 

Sophie
