### ISSUE TITLE
Question Regarding Formulation for Area Elasticity, Perimeter Elasticity, and Line Tension

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#233]
In the effector classes, each energy term is divided by 2 or multiplied by 0.5. Is this to account for the half-edges since each edge would be counted twice, or is that part of the governing equation that is implemented? 

The line tension effector mentions that it considers the half-edges and thus divides by two. Is that also the case for the other two effectors? I ask because I am working on some custom effectors myself and am a little confused as to whether I should also divide the energy functions by two for the ones that generate an edge-based gradient/energy dataframe. 

Thanks, 
Tasnif

**Comment by glyg** [comment]
HI @sniffo - For the line tension, the factor of two is there to account for both half-edges, although we could arguably do without. I think the objective at implementation time was to be close to Farhadifar et al. - As for elastic effectors, it is more a matter of the classical definition of Hooke's law:
$$
U = \frac{K}{2}(x - x_0)^2, F = -\partial U / \partial x U = -K(x - x_0)
$$

So the 1/2 term in the potential is to avoid a factor 2 in the force.

G

**Comment by glyg** [comment]
PS: if you are not familiar with LaTeX, copy-paste the answer above in a markdown cell in a notebook to have rendering :)

**Comment by sniffo** [comment]
Ahh I see, that makes a lot more sense thank you.
