### ISSUE TITLE
Last version of pandas (1.3.5) not working with Tyssue

### ISSUE THREAD

**Issue by sophietheis** [DamCB/tyssue#256]
Hi, 

It seems that the last version of pandas doesn't work with the last version of pandas (test with 1.3.5). 
I check with the repo tyssue-demo and my_binder, and when I try to generate an ellipsoid sheet, I've got the error 
```TypeError: 'set' type is unordered```
I test pandas version 1.3.2 and I've got the same error message. 
I know that it works with the version 1.2.0 of pandas. 
Maybe some versions between 1.2.0 and 1.3.2 works, but I don't know which one... 

Sophie

**Comment by glyg** [comment]
Thanks for the report @sophietheis ! Can you put the whole traceback so we know where the bug is?

usually replacing `set` by `frozenset` fixes that kind of issue

Also maybe we can add a regression test at that bug, always a good thing to do ;)

**Comment by glyg** [comment]
ok replacing `set` with `np.unique` should be ok, but maybe it is not so useful to always  keep the original face and vertex index — I don't think I ever used those columns. Actually elsewhere we explicitly say we do not track vertex and face indices.  So we can maybe make that chunk of code optional with a deprecation warning.

I'll try to find time this summer to tidy tyssue up a bit, and I'll fix that if you don't have time right now 

Thanks again for the report 
cheers

**Comment by glyg** [comment]
This has been fixed in the commits I made in the last days
