### ISSUE TITLE
Planar periodic sheet

### ISSUE THREAD

**Issue by Lepinja666** [DamCB/tyssue#260]
Hi, 
I want to work with a planar periodic sheet, but somehow the "update_all()" function always shrinks the sheet by 2 rows and 2 columns and adds these weird lines connecting non-adjacent vertices. 

**The code is simply:**

from tyssue import Sheet, config
from tyssue import PlanarGeometry as geom
from tyssue.dynamics.planar_vertex_model import PlanarModel as model
from tyssue.io import hdf5
from tyssue.draw.plt_draw import sheet_view

h5store = r'C:\Users\user\pythonProject1\venv\Lib\site-packages\tyssue\stores\planar_periodic8x8.hf5'
datasets = hdf5.load_datasets(h5store, data_names=['face', 'vert', 'edge'])
specs = config.geometry.planar_periodic_sheet()
sheet = Sheet('sheet', datasets, specs)

fig, ax = sheet_view(sheet)

geom.update_all(sheet)
fig, ax = sheet_view(sheet)

geom.update_all(sheet)
fig, ax = sheet_view(sheet)

geom.update_all(sheet)
fig, ax = sheet_view(sheet)

**Output:**
![output1](https://user-images.githubusercontent.com/113996668/194849740-50eee4df-160c-4e2b-a5dc-372dc39715a0.png)
![output2](https://user-images.githubusercontent.com/113996668/194849765-03d6262e-3640-4f9b-abc5-6a0a3332b2dd.png)
![output3](https://user-images.githubusercontent.com/113996668/194849759-09a6addc-0f0f-49f2-82a6-dd9aca20d39a.png)
![output4](https://user-images.githubusercontent.com/113996668/194849751-52e01294-8460-4081-b990-b848bae8295f.png)

Thank you in advance!

**Comment by sophietheis** [comment]
Hi, 

The problem is in boundaries values in the settings. I think by default it is set as x=[-1,1] and y=[-1,1]. That's why your tissue is reduced. 
You can see boundaries values with `sheet.settings['boundaries']`.
You can update those values before create the sheet : 
```python
specs = config.geometry.planar_periodic_sheet()
specs["settings"]["boundaries"] = {"x": [-0.5, 8.5], "y": [-0.5, 8.5]}
sheet = Sheet("periodic", dsets, specs)
```

It should solve your problem. :)

**Comment by Lepinja666** [comment]
Dear Sophie,

Thank you so much! 
Is there maybe a way to make the boundary faces not stretched out when updating the geometry? 
![output5](https://user-images.githubusercontent.com/113996668/194859481-6bf91746-925c-4778-9064-bf4efbdf2585.png)
Also, is there a simple way of generalizing this model to an arbitrary number of cells (not 8x8)?

**Comment by sophietheis** [comment]
Maybe the boundary value is a bit too far away. you can try 8 or 8.1 instead of 8.5. 

Sure, you can generate tissue with the number of cells that you want. 
You can use : ` sheet = Sheet.planar_sheet_2d( 'sheet', nx=10, ny=10, distx=1, disty=1, noise=0.5)`
`nx` and `ny` are the number of cells in the x and y axis. If you want regular sheet, set noise value to 0.

We also advise to run this line after `sheet.sanitize(trim_borders=True)` to avoid strange cell at the border of the tissue.

**Comment by Lepinja666** [comment]
Just one more question,
how can these PBC specs then be applied to the arbitrary sheet?
If I apply them after the sheet is created (with **sheet.update_specs(specs)**) I just get some horrible mess.

**Comment by Lepinja666** [comment]
I went through the notebook, it was very instructive :)
Here, the problem with **Sheet.planar_sheet_2d()** is that it cannot accept **specs** as an argument, so I should use **Sheet("periodic", datasets, specs)**, but I don't know how to manually create **datasets** myself.

**Comment by sophietheis** [comment]
If you want only the dataset, you can try : 
``` python
from tyssue.generation import from_2d_voronoi, hexa_grid2d
grid = hexa_grid2d(nx, ny, distx, disty, noise)
datasets = from_2d_voronoi(Voronoi(grid))
 ```

**Comment by glyg** [comment]
Hi @Lepinja666 thank you for your interest in tyssue, thank you @sophietheis for the feedback. PBC would deserve some work over to be more intuitive / easy to use. 

The datasets are "just" pandas dataframes that need to be correctly indexed, you can look into the `from_2d_voronoi` code to see how it is done there

**Comment by Lepinja666** [comment]
Thank you both for such quick responses :)
Would it be possible for me to have a look at the code that produced the **planar_periodic8x8** dataset? Because what I need is exactly the same thing with just a few more cells.

**Comment by glyg** [comment]
Ok, seems the code is there, but depends on a custom cgal-to-python bridge:
https://github.com/DamCB/tyssue-notebooks/blob/master/research/PeriodicBoundaryConditions.ipynb

Frankly I do not remember when I wrote that and if this has any chance to work. My recollection is that Delaunay triangulation (and its reciprocal Voronoi) are not implemented with periodic boundary conditions in scipy, so I had to resort to cgal.
You can have a look, maybe it runs, but maybe there is a way to simplify that, do it differently, or find a better cgal-to-python wrapper or a good 2D periodic Delaunay tessalation...

Sorry this is not easier,

**Comment by glyg** [comment]
Also you can add cells to the 8x8 grid by doing divisions, but you won't get a hexagonal tissue

**Comment by Lepinja666** [comment]
Thanks so much, I'll try to make it work :)
