### ISSUE TITLE
Use collision solver change QS result

### ISSUE THREAD

**Issue by sophietheis** [DamCB/tyssue#262]
Seems that I obtain different results using `with_collisions` or not with QS solver and from the first minimum energy equilibrium.
The only difference between the two simu is to set `with_collisions` parameter to `True` or `False` in the `QSSolver`. Everything else is identical.
 
My original tissue before any equilibrium : 
![image](https://user-images.githubusercontent.com/17041165/199060456-d8cc9b7a-6a32-4fcd-894e-edbf4ebed9e6.png)

One minimum energy equilibrium WITHOUT collision
![image](https://user-images.githubusercontent.com/17041165/199060314-30c965d6-f398-48f1-a2d8-ce30099ee04e.png)

One minimum energy equilibrium WITH collision
![image](https://user-images.githubusercontent.com/17041165/199060529-dc81babb-0c3c-46c3-aa40-6bea56ef887d.png)

Maybe, it is due to my tissue, which is a subclass of Sheet class. But, as I don't have any collision at the beginning, I don't know why it change the result... 
I just change `solvers.py` file to be able to detect collisions both in 2D and in 3D tissue (as it works only for 2.5D sheet/3D monolayer) (Basically I replace `list("xyz")` by `self.sheet.coords`). Maybe it's not enough and have to write something specific for 2D. Will try to find the problem/solution this week.

**Comment by sophietheis** [comment]
Found the problem. Collision solver, and specifically CGAL recquires 3D coordinates, and I gave 2D coordinate. It didn't raise any error, I think there is a reshaping of 2D coordinates into 3D coordinates, but there must be some value missing... So I am surprise that no error was raised.

**Comment by glyg** [comment]
Maybe for now just disable collision detection, it is not working so well any way. 
At some point we should switch to a CGAL backend for the whole geometry I guess?

**Comment by sophietheis** [comment]
Yes, but I need collision solver, because later tissue fold and collide...
But indeed result is quite unstable from one simulation to another. 
What do you mean by switching to a CGAL backend  for the whole geometry?

**Comment by sophietheis** [comment]
I think fixing the problem in 2D will be much easier than fixing it in 3D. 
Well, only if intersections are properly detected... Because here, `self_intersection` is happy and tell me that there is no intersection... Well I am strongly disagree... :unamused: 
![image](https://user-images.githubusercontent.com/17041165/200616426-5b82bc3c-ec32-413a-8601-939b14ad70a4.png) 
![image](https://user-images.githubusercontent.com/17041165/200618071-fdeb6569-ff8e-421b-ac7b-6ad1b2e131d8.png)

**Comment by glyg** [comment]
yes `self_intersection` is broken ! I did not get to finish implementing the algorithm I think! 
Do you think you can work on the implementation?

**Comment by sophietheis** [comment]
Sure, No problem. :)

**Comment by sophietheis** [comment]
Good news, `self_intersection` was easy to fix. It appears that `surface_mesh` was created with only 1/3 of total cells. 
Bad news, position correction is wrong. It moves some vertex that doesn't need to be moved, and moves some vertex very far away... And, well it is complicated to solve intersection in 3D... I left out as I don't need to solve in 3D for now...

So, to get around the problem, I write something for 2D intersection which correspond to :
1. get 2 intersected junctions
2. get 2 triangles correspond to the 2 intersected junctions
3. Find which vertex is inside which triangle (I assume that almost all the time there is 1 vertex that penetrate to another cell)
4. Calculate intersection between one junction and segment (vertex, cell center)
5. Move the vertex to the intersection

Of course, few things can be improve such as not sticking the vertex to the intersection coordinates... 
But it seems to work pretty well :smile: 
![image](https://user-images.githubusercontent.com/17041165/201151460-e2433ed6-6791-48fd-8402-21154f5afade.png)

**Comment by glyg** [comment]
this is great!!! Can you open a PR, I'll try to review it next week :) ?

**Comment by glyg** [comment]
regarding the general 3D collision, I think we rather should work on computing the surface distance computation in CGAL and derive a potential, so a lot more work :)
