### ISSUE TITLE
Value out of range for T1 transition (ValueError, KeyError) - Periodic sheet

### ISSUE THREAD

**Issue by Lepinja666** [DamCB/tyssue#265]
Hi!
I'm working on my 2D sheet with periodic boundaries and whenever I am doing lots of T1 transitions (and also divisions) and avoiding the edges on the boundaries:
```
for edge, data in sheet.edge_df.iterrows():
       if data.length < some_threshold_length and data.at_x_boundary == False and data.at_y_boundary == False:
            t1_edge = edge
            type1_transition(sheet, t1_edge)
            sheet.reset_index(order=True)
            geom.update_all(sheet)
```
I eventually get a **ValueError/KeyError** for some number around 400 (in the example below, this number is 396). It seems as the bigger the **some_threshold_length**, the quicker the error occurs, maybe just because the T1 transitions are more likely to happen.
```
ValueError                                Traceback (most recent call last)
File c:\Users\user\anaconda3\lib\site-packages\pandas\core\indexes\range.py:385, in RangeIndex.get_loc(self, key, method, tolerance)
    384 try:
--> 385     return self._range.index(new_key)
    386 except ValueError as err:

ValueError: 396 is not in range

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
    t1_edge = edge
    backup = copy.deepcopy(sheet)
--> type1_transition(sheet, t1_edge)
    sheet.reset_index(order=True)
...
--> 387             raise KeyError(key) from err
    388     raise KeyError(key)
    389 return super().get_loc(key, method=method, tolerance=tolerance)

KeyError: 396
```
Thank you in advance for any suggestion!

**Comment by sophietheis** [comment]
Hi, 

You made a loop on `sheet.edge_df`, but this dataframe is changed inside the loop. I think that's why you got this error. You can 
check the size of `sheet.edge_df` to see if key 396 still exist or not. 

The error should disappear if you replace the for loop by a while loop.

Sophie

**Comment by Lepinja666** [comment]
Makes sense, thank you!
