### ISSUE TITLE
Cannot scale periodic boundary sheet

### ISSUE THREAD

**Issue by Lepinja666** [DamCB/tyssue#266]
Another issue that I have come across:
A periodic boundary sheet doesn't scale when one applies:
```
geom.scale(sheet, 1.5, list('xy'))
geom.update_all(sheet)
```
This becomes annoying when cells are dividing and there is more and more of them while the size of the system is the same, so the cells are becoming smaller and smaller. I solved this by also decreasing the prefered areas and prefered perimeters of the cells, so that the nature of the dynamics remained the same, but this solution feels kind of "ugly".

**Comment by sophietheis** [comment]
I think that as you already have `boundaries` in your settings, [`update_dcoords`](https://github.com/DamCB/tyssue/blob/master/tyssue/geometry/base_geometry.py#L21) (which is called when you do [`geom.update_all`](https://github.com/DamCB/tyssue/blob/master/tyssue/geometry/planar_geometry.py#L10) don't update periodic coord. You can try to call it specifically by doing [`geom.update_periodic_dcoords(sheet)`. ](https://github.com/DamCB/tyssue/blob/master/tyssue/geometry/base_geometry.py#L113)

**Comment by Lepinja666** [comment]
Is it possible to use `PlanarGeometry` and `base_geometry` together? Because `base_geometry` doesn't have the `update_all(sheet)` function which I also often need and `PlanarGeometry` doesn't have the `update_periodic_dcoords(sheet)` function.

**Comment by sophietheis** [comment]
We use inheritance in Tyssue, meaning that `PlanarGeometry` class is a child of `BaseGeometry` class and we can use functions present in `BaseGeometry` with `PlanarGeometry`. 
If you are not familiar with inheritance I think this link explain it quite well : [inheritance](https://www.digitalocean.com/community/tutorials/understanding-class-inheritance-in-python-3)

**Comment by Lepinja666** [comment]
Thanks! However the `update_periodic_dcoords(sheet)` is also not in the `BaseGeometry` class. It is located in the `base_geometry.py` file of the library, but it is outside the `BaseGeometry` class. So one has to access this function separately by calling `base_geometry.update_periodic_dcoords(sheet)`.
