### ISSUE TITLE
Prevent a print when setting up specs

### ISSUE THREAD

**Issue by Lepinja666** [DamCB/tyssue#268]
Hi, I just want to prevent the text below from being printed, because I am running thousands of simulations and it gets annoying. I can't seem to find where and in which function these lines are printed.
```
Reseting column ux of the edge dataset with new specs
Reseting column uy of the edge dataset with new specs
Reseting column is_alive of the face dataset with new specs
Reseting column perimeter of the face dataset with new specs
Reseting column is_active of the vert dataset with new specs
```
Thank you in advance!

**Comment by Lepinja666** [comment]
I've already tried
`sys.stdout = open(os.devnull, 'w')`
and it didn't work.

**Comment by Lepinja666** [comment]
Okay, I've tried this and the text is still printed.
And `logger.propagate = False` also doesn't do the trick.

**Comment by sophietheis** [comment]
Maybe you can try what is proposed here : [https://stackoverflow.com/questions/28694540/python-default-logger-disabled/28694704#28694704](https://stackoverflow.com/questions/28694540/python-default-logger-disabled/28694704#28694704) .
