### ISSUE TITLE
Definition of ux, uy

### ISSUE THREAD

**Issue by Lepinja666** [DamCB/tyssue#270]
Hi, this might not belong here, but I can't seem to find a straight answer elsewhere:
What exactly are `ux` and `uy` in the edge Dataframe?

**Comment by btbest** [comment]
See `update_uccords` in [base_geometry.py](https://github.com/DamCB/tyssue/blob/4e80a95a53c5e5c472105abcc6b54900a1ee52f1/tyssue/geometry/base_geometry.py).

`dcoords `are a vector pointing from the edge's source vertex to its target vertex. `ucoords `are the same coordinates, normalised by the edge's length. So it's a unit vector aligned with the edge.

**Comment by Lepinja666** [comment]
Thank you!
