### ISSUE TITLE
History.retrieve() efficiency. Any workarounds?

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#273]
I've been working on some simulation analysis on saved History objects and realized that loading a specific set of datasets takes about 2 seconds. Iterating over thousands of time-steps takes hours, depending on the temporal resolution and simulation length. Any idea where the bottleneck might be or suggestions on how to work around this? I need to be able manipulate the dataframes to a certain degree.

**Comment by sophietheis** [comment]
I looked and here are a few ideas : 
    - `history.retrieve(history.time_stamps[time_id])` takes more time than using `history.retrieve(time)`. About +0.3s for my small datasets (1000time points, ~700 cells, 1400 vertices). 
    - there is a for loop to retrieve the selected datasets [here](https://github.com/DamCB/tyssue/blob/master/tyssue/core/history.py#L447). You can replace it by a list comprehension : `sheet_datasets={key:pd.read_hdf(self.hf5file, key=key, where=f"time == {time}") for key in self.datasets.keys()}
` . List comprehension are generally faster than loop. I don't see any impact on my calculation time for my dataset, maybe this will help with a larger dataset. 

If you use jupyter notebook, you can use snakeviz ([https://jiffyclub.github.io/snakeviz/](https://jiffyclub.github.io/snakeviz/)) at the beginning of one cell to see which part of the `retrieve` function is the most time-consuming part. 

I hope this helps. 

Sophie

**Comment by sniffo** [comment]
Hi Sophie, 

Thank you for your suggestions! I have been using `history.retrieve(time)` so that should not be an issue. My datasets are about the smaller than yours (400 cells, 800 vertices) so the list comprehension is likely not going to do much. However, the snakeviz analysis seems to be quite useful, indicating that most of the time is taken by the `time_stamps(self, element="vert")` method. Looking at `history.retrieve()` I'm not quite sure this `time_stamps()` method is being called, but the pytables `select` method within it is causing the bottleneck.

![Screenshot from 2023-11-02 09-50-09](https://github.com/DamCB/tyssue/assets/20935700/5662e8a5-03aa-4dc6-ad1f-7acdbbe45a01)

Any thoughts would be appreciated.

**Comment by glyg** [comment]
Hi @sniffo if you look in the code, `time_stamps` is defined as a `@property`, so it is called every time it's called, maybe just computing it at the instanciation of `HistoryHdf5` is enough? (not sure if that does not bug when writing)

You can patch historyhdf5 with

class FastHistoryHDF5(HistoryHdf5):

**Comment by sniffo** [comment]
I've implemented the following.

`
class FastHistoryHDF5(HistoryHdf5):
    def __init__(self,
        sheet=None,
        save_every=None,
        dt=None,
        save_only=None,
        hf5file="",
        overwrite=False,
    ):
        
        super().__init__()
        with pd.HDFStore(self.hf5file, "r") as file:
            self._time_stamps = file.select("vert", columns=["time"])["time"].unique()

    @property
    def time_stamps(self):
       return self._time_stamps
`
But run into a minor issue of a time_stamps method call prior to running this code. Simple inheritance might not do the trick.

`
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_1324140/3970972349.py in <module>
----> 1 history = FastHistoryHDF5.from_archive("CW_0.5_1.hf5")

~/anaconda3/envs/tyssueflat/lib/python3.7/site-packages/tyssue/core/history.py in from_archive(cls, hf5file, columns, eptm_class)
    321         eptm = eptm_class(hf5file.name, datasets)
    322         eptm.settings.update(settings)
--> 323         return cls(sheet=eptm, hf5file=hf5file, overwrite=True)
    324 
    325     @property

~/anaconda3/envs/tyssueflat/lib/python3.7/site-packages/tyssue/core/history.py in __init__(self, sheet, save_every, dt, save_only, hf5file, overwrite)
    427     ):
    428 
--> 429         super().__init__()
    430         with pd.HDFStore(self.hf5file, "r") as file:
    431             self._time_stamps = file.select("vert", columns=["time"])["time"].unique()

~/anaconda3/envs/tyssueflat/lib/python3.7/site-packages/tyssue/core/history.py in __init__(self, sheet, save_every, dt, save_only, hf5file, overwrite)
    286                         break
    287         if sheet is None:
--> 288             last = self.time_stamps[-1]
    289             with pd.HDFStore(self.hf5file, "r") as file:
    290                 keys = file.keys()

~/anaconda3/envs/tyssueflat/lib/python3.7/site-packages/tyssue/core/history.py in time_stamps(self)
    433     @property
    434     def time_stamps(self):
--> 435        return self._time_stamps
    436 
    437 def _retrieve(dset, time):

AttributeError: 'FastHistoryHDF5' object has no attribute '_time_stamps'
`
The `last` variable does not seem like it is used anywhere, I might be wrong.

**Comment by glyg** [comment]
you need to reimplement also the from_archive classmethod (or change the class directly, if you don't mind using tyssue from source)

**Comment by sniffo** [comment]
I did edit the class directly and it works, run time went from around 2-4 seconds to about 0.03 seconds. I was more wondering how you'd like me to handle the PR.

**Comment by glyg** [comment]
Well I think this implementation is better, I don't know if there are side effects when writing, but we can look at that with tests (which I will set back up soon, promise ;))

**Comment by sniffo** [comment]
#274

**Comment by sniffo** [comment]
Done!
