### ISSUE TITLE
Using T1 Transitions instead of reconnect?

### ISSUE THREAD

**Issue by sniffo** [DamCB/tyssue#282]
I am runnning some simulations where I would like the merge-split based reconnection system implemented by default in the euler solver with a simple T1 transition - since the settings I'm using causes rosettes to form a lot faster than they can be resolved. I would also like to analyze the difference between rosette based transitions and simple T1 transitions for a set of simulations I have already performed and analyzed. Is there an easy what to do this?

**Comment by glyg** [comment]
Hi @sniffo 

Three parameters govern reorganization:
The threshold length (`sheet.settings["threshold_length"]`), and the reconnect frequencies `sheet.settings["p_4"]` and `sheet.settings["p_5"]`

If you set p_4 to 1, this means that the 'split' from a range 4 vertex will be instantaneous, corresponding to a type 1 transition 
 

If you have time, could you test the `dev` branch here? I merged you PR and @sophietheis 's and changed the packaging?

**Comment by sniffo** [comment]
Hi Guillame, 

Thanks for the suggestion. But is it not the case that the split has a 50% chance of it reforming the original edge that collapsed to form the rosette in the first place? This would still be a significant improvement regardless. 

Yes, I would be happy to help with the test later this week.

**Comment by glyg** [comment]
> Thanks for the suggestion. But is it not the case that the split has a 50% chance of it reforming the original edge that collapsed to form the rosette in the first place? This would still be a significant improvement regardless.

Yes you're right, I hadn't thought about that. At the very least it should prevent rosettes. The less easy alternative is to change the `reconnect` behavior that is called by the solver (so sub-classing `EulerSolver` to run the T1s

> Yes, I would be happy to help with the test later this week.

Great! 
You need to :
```sh
git fetch
git switch dev
pip install .[dev] # editable install is broken don't use -e
make tests
```
And then try your code :)

Best

Guillaume
