### ISSUE TITLE
Pandas/numpy C++ interface

### ISSUE THREAD

**Issue by glyg** [DamCB/tyssue#5]
First of all pandas is pure python, so I imagine it's just something like `boost::python::object` matter to retrieve column names, and them resorting to `numpy` for managing the data itself

We have two solutions here:

* https://github.com/ndarray/Boost.NumPy
and:
* https://github.com/mdboom/numpy-boost

**Comment by hadim** [comment]
About Boost.Numpy, two things you should want to do:

- add the include and the lib here https://github.com/CellModels/tyssue/blob/master/src/cpp-tyssue/CMakeLists.txt#L8 and here https://github.com/CellModels/tyssue/blob/master/src/cpp-tyssue/CMakeLists.txt#L25

- create a conda recipe for Boost.NumPy and upload it to https://conda.anaconda.org/ so people can easyly install it inside the virtualenv

**Comment by glyg** [comment]
Thanks. I'll do this when I'm back from the weekend.

G.

Le 10 juillet 2015 18:24:50 GMT+02:00, Hadrien Mary <notifications@github.com> a écrit :
>About Boost.Numpy, two things you should want to do:
>
>- add the include and the lib here
>https://github.com/CellModels/tyssue/blob/master/src/cpp-tyssue/CMakeLists.txt#L8
>and here
>https://github.com/CellModels/tyssue/blob/master/src/cpp-tyssue/CMakeLists.txt#L25
>
>- create a conda recipe for Boost.NumPy and upload it to
>https://conda.anaconda.org/ so people can easyly install it inside the
>virtualenv
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/CellModels/tyssue/issues/5#issuecomment-120451083

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by glyg** [comment]
Ok, one more solution:
http://docs.cython.org/src/userguide/wrapping_CPlusPlus.html

Maybe cython makes sense, asked about that on the scipy mailing list (I'll repost on cython-user if I don't have answers there).

As even a simple test fails with Boost.Numpy for now, maybe it's worth giving it a try. I know there are SWIG bindings for parts of CGAL, but I really don't like SWIG.

**Comment by glyg** [comment]
Eventually, I'm not sure I'll need CGAL anytime soon. When I need it, I'll most certainly use cython
