### ISSUE TITLE
Problem with Running Example Notebook Basic_Usage

### ISSUE THREAD

**Issue by minamdar** [DamCB/tyssue#54]
I am using the most recent version of tyssue (0.2.rc1.dev0+a69d5c1). However,
I am have some problems running the most basic code (Basic_Usage.ipynb).
Specifically, the problem occurs during the Energy Minimisation step:

res = Solver.find_energy_min(sheet, PlanarGeometry, PlanarModel)

The result of

print(res['success'])

is 'False'

Even more specifically, I can see that, at the end of the minimisation step,
the vertices at the boundaries do not move at all. This is quite unlike the
picture which I see in the Documentation:

http://tyssue.readthedocs.io/en/latest/notebooks/Basic_Usage.html#Easy-creation-of-a-2D-epithelial-sheet

after Energy Minimisation (In [11]:).

Am I doing something stupid? Could you please help?

BTW, over the last couple of months I have experimented quite a bit with
tyssue, and really like what you have done. I have also been successfully able
to run number of example Notebooks, and indeed understand the general
framework. That said, I have been having specific troubles in executing some
of the notebooks. So I am finally collecting my questions and planning to ask
them to you one-by-one -- the question above is being the first.

Thank you very much in advance for your help.
best,
mandar

**Comment by glyg** [comment]
Hey, thanks for the bug report!

It should be fixed by   9e0f74908fbeff8892f5a227ff829bf3b1aa2165

**Comment by glyg** [comment]
closed by 9e0f749
