### ISSUE TITLE
Problem running 3D part of Cell_Division.ipynb

### ISSUE THREAD

**Issue by minamdar** [DamCB/tyssue#55]
There is some problem running Cell_Division.ipynb. 

The specific problem occurs for Division in 3D Epithelium, when the cell
division is undertaken as per In [24]:  

http://tyssue.readthedocs.io/en/latest/notebooks/Cell_Division.html#Division-in-a-3D-single-layer-epithelium

This gives error with the following traceback:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-d0062277b19f> in <module>()
      1 mother = 8
      2 daughter = cell_division(monolayer, mother, 
----> 3                          orientation='vertical')

~/anaconda3/envs/fenty/lib/python3.6/site-packages/tyssue-0.2rc1-py3.6.egg/tyssue/topology/monolayer_topology.py in cell_division(monolayer, mother, orientation, psi)
     63 
     64     daughter = bulk_division(monolayer, mother,
---> 65                              MonoLayerGeometry, vertices)
     66 
     67     # Correct segment assignations for the septum

~/anaconda3/envs/fenty/lib/python3.6/site-packages/tyssue-0.2rc1-py3.6.egg/tyssue/utils/decorators.py in with_bckup(*args, **kwargs)
      7     def with_bckup(*args, **kwargs):
      8         eptm = args[0]
----> 9         eptm.backup()
     10         try:
     11             return func(*args, **kwargs)

~/anaconda3/envs/fenty/lib/python3.6/site-packages/tyssue-0.2rc1-py3.6.egg/tyssue/core/objects.py in backup(self)
    184         """
    185         log.info('Backing up')
--> 186         self._backups.append(self.copy(deep_copy=True))
    187 
    188     def restore(self):

~/anaconda3/envs/fenty/lib/python3.6/site-packages/tyssue-0.2rc1-py3.6.egg/tyssue/core/objects.py in copy(self, deep_copy)
    175         identifier = self.identifier+'_copy'
    176         new = type(self)(identifier, datasets,
--> 177                          specs=self.specs, coords=None)
    178         return new
    179 

TypeError: __init__() got an unexpected keyword argument 'coords'

**Comment by glyg** [comment]
Ok, this comes from #53, all the more reason to fix it now :-)

**Comment by glyg** [comment]
so the first bug was fixed, but a sneaky one popped out right behind, I think I'll need some more time to get it right... Has to do with vertices ordering during division.

**Comment by minamdar** [comment]
No problem Guillaume. I understand that the various parts of the code are connected, but is there some place where the current bug is localised. Maybe, I can also independently have a look — would also help me understand the code-structure in more detail. 

thanks,
mandar

**Comment by glyg** [comment]
Hi Mandar

If you want to have a look, I think the problem lies in the `get_division_vertices` function in the `bulk_topology` module. This function must return the vertices of the edges that will be cut by the division plane and they are supposed to be ordered in a direct orientation. This is not the case, and thus the division produces an invalid epithelium.

To examine that, I usually copy/paste the bad function in the notebook to tinker with it easily.

Best,

Guillaume

**Comment by minamdar** [comment]
Thanks Guillaume, and sorry for the delated reply — I was travelling. 

I will work into it and get back to you.

best,
mandar

**Comment by glyg** [comment]
No worries, I was away too,

If you want, I just pushed some code in my fork: https://github.com/glyg/tyssue/ . I modified the `do_undo` decorator code a bit to be able to examine the faulty epithelium, and started exploring the problem in the Cell_Division notebook from the doc.

Tell me what you think

Best

Guillaume

**Comment by glyg** [comment]
No worries, I was away too,

If you want, I just pushed some code in my fork: https://github.com/glyg/tyssue/ . I modified the `do_undo` decorator code a bit to be able to examine the faulty epithelium, and started exploring the problem in the Cell_Division notebook from the doc.

Tell me what you think

Best

Guillaume

**Comment by glyg** [comment]
Hi @minamdar sorry if this stalls a bit, I got caught up in other businesses las weeks. I hope this doesn't discourages you to work on tyssue :/
I'm back on the library full time this week, so thing should go back on track !

**Comment by minamdar** [comment]
No worries, Guillaume! I am slowly working to understand to working of your excellent code. My understanding of mechanics is reasonable, but I am still learning python. But I am slowly learning :)

thanks,
mandar
