### ISSUE TITLE
No module quantities

### ISSUE THREAD

**Issue by vvelagal** [DamCB/tyssue#86]
import quantities as pq

ModuleNotFoundError: No module named 'quantities'

Can you help me?

**Comment by glyg** [comment]
Hi,
You need to do in a terminal `conda install -c conda-forge quantities` if you used conda to install, or `pip install quantities` if you used only pip.

Can you tell me to what method you used to install tyssue, so that I can update the instructions?

**Comment by vvelagal** [comment]
I used conda  method to install tysssue.

**Comment by glyg** [comment]
Ok thanks!

Is it working now?

**Comment by vvelagal** [comment]
No,it is not working.I tried to reinstall and I am getting the following error.


conda-forge::ipywebrtc-0.4.1-py37_1'.
LinkError: post-link script failed for package conda-forge::ipywebrtc-0.4.1-py37_1
running your command again with `-v` will provide additional information
location of failed script: /home/vijay/anaconda3/bin/.ipywebrtc-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::ipywebrtc-0.4.1-py37_1
running your command again with `-v` will provide additional information
location of failed script: /home/vijay/anaconda3/bin/.ipywebrtc-post-link.sh
==> script messages <==
<None>

**Comment by glyg** [comment]
It seems the latest version of tyssue didn't build for python 3.7, I'll try to fix that now

**Comment by vvelagal** [comment]
Can you please let me know once it is fixed?

**Comment by glyg** [comment]
Of course.

In the mean time, you can try with python 3.6

```bash
conda create -n py36 python=3.6
source activate py36 # you should see py36 at the beginning of you terminal prompt
conda install -c conda-forge tyssue
```

**Comment by glyg** [comment]
Hi @vvelagal - The 3.7 version of the package should be available through conda-forge now (at least on linux and MacOS boxes). 

There is an issue with Windows build:
https://ci.appveyor.com/project/conda-forge/tyssue-feedstock/branch/master

but it should not impact you.

Can you tell me if it works for you (either with 3.6 or 3.7)

**Comment by vvelagal** [comment]
Thanks its working now.
